language: python
python:
  - 2.7.10

compiler:
  - gcc

#blacklist:
branches:
  except:
    - dev
    - bond_clas

#whitelist:
branches:
  only:
    - master
    - stable

git:
  submodules:
    false

before_install:

  #To install LoProp for Dalton

  - git clone https://github.com/vahtras/loprop.git
  - cd loprop
  - python setup.py install
  - cd ..
  #// LoProp
  - sudo apt-get update -qq
  - sudo apt-get install blas atlas libhdf5-serial-dev
    #- sudo apt-get install gcc
  - git submodule update --init --recursive

install:
  - pip install --upgrade setuptools
  - pip install coveralls matplotlib numpy cython h5py applequist

#Build cythonized version of particles solver
#before_script:
#  - cd src/pd
#  - python setup.py build_ext --inplace
#  - cd ../..

script: 
  nosetests -a 'type=!cython' -a 'speed=!slow' -a 'speed=fast' --cover-erase --with-coverage --cover-package=pdbreader,molecules,read_dal,template,ut
after_success:
  coveralls


